import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../../core/constants/app_colors.dart';

class FullSummaryScreen extends StatelessWidget {
  final String title;
  final String channelName;
  final String thumbnailUrl;
  final String content;
  final String videoUrl;
  final bool isTranscript;
  final String? channelProfileSummary;
  final List<String> previousSummaries;

  const FullSummaryScreen({
    super.key,
    required this.title,
    required this.channelName,
    required this.thumbnailUrl,
    required this.content,
    required this.videoUrl,
    required this.isTranscript,
    this.channelProfileSummary,
    this.previousSummaries = const [],
  });

  Future<void> _launchYouTubeVideo(BuildContext context) async {
    final Uri url = Uri.parse(videoUrl);
    if (!await launchUrl(url, mode: LaunchMode.externalApplication)) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Could not open YouTube link: $videoUrl')),
        );
      }
    }
  }

  void _copyText(BuildContext context) {
    Clipboard.setData(ClipboardData(text: content));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Copied to clipboard!')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.background,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close, color: AppColors.textDark),
          onPressed: () => Navigator.pop(context),
        ),
        centerTitle: true,
        title: Text(
          isTranscript ? 'Full Transcript' : 'Full Summary',
          style: const TextStyle(color: AppColors.textDark, fontWeight: FontWeight.bold, fontSize: 18),
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  CachedNetworkImage(
                    imageUrl: thumbnailUrl,
                    width: double.infinity,
                    height: 220,
                    fit: BoxFit.cover,
                    placeholder: (context, url) => Container(color: Colors.grey[200]),
                  ),
                  
                  Padding(
                    padding: const EdgeInsets.all(24.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          title,
                          style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: AppColors.textDark, height: 1.3),
                        ),
                        const SizedBox(height: 12),
                        Text(
                          channelName.toUpperCase(),
                          style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.textGrey, letterSpacing: 1.0),
                        ),
                        
                        const SizedBox(height: 32),
                        
                        if (!isTranscript)
                          Container(
                            padding: const EdgeInsets.only(left: 16),
                            decoration: const BoxDecoration(
                              border: Border(left: BorderSide(color: AppColors.primaryRed, width: 3)),
                            ),
                            child: const Text(
                              'Insights generated by TubeSum AI.',
                              style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: AppColors.textDark),
                            ),
                          ),
                        
                        const SizedBox(height: 24),
                        Text(
                          content,
                          style: const TextStyle(
                            fontSize: 16,
                            color: Color(0xFF333333),
                            height: 1.6,
                          ),
                        ),

                        if (!isTranscript && channelProfileSummary != null && channelProfileSummary!.isNotEmpty) ...[
                          const SizedBox(height: 40),
                          const Text(
                            'ABOUT THE CREATOR',
                            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w800, color: AppColors.textGrey, letterSpacing: 1.2),
                          ),
                          const SizedBox(height: 12),
                          Text(
                            channelProfileSummary!,
                            style: TextStyle(fontSize: 14, color: AppColors.textDark.withOpacity(0.8), height: 1.5),
                          ),
                        ],

                        if (!isTranscript && previousSummaries.isNotEmpty) ...[
                          const SizedBox(height: 40),
                          const Text(
                            'PREVIOUS CONTEXT',
                            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w800, color: AppColors.textGrey, letterSpacing: 1.2),
                          ),
                          const SizedBox(height: 12),
                          ...previousSummaries.map((summary) => Padding(
                            padding: const EdgeInsets.only(bottom: 12.0),
                            child: Container(
                              padding: const EdgeInsets.all(12),
                              decoration: BoxDecoration(
                                color: AppColors.buttonGrey.withOpacity(0.5),
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Text(
                                "• $summary",
                                style: const TextStyle(fontSize: 13, color: AppColors.textDark, fontStyle: FontStyle.italic),
                              ),
                            ),
                          )).toList(),
                        ],
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, -5))
              ],
            ),
            child: SafeArea(
              child: Column(
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: ElevatedButton.icon(
                          onPressed: () => _copyText(context),
                          icon: const Icon(Icons.copy, size: 18),
                          label: const Text('Copy Text'),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.buttonGrey,
                            foregroundColor: AppColors.textDark,
                            elevation: 0,
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: ElevatedButton.icon(
                          onPressed: () {}, 
                          icon: const Icon(Icons.share, size: 18),
                          label: const Text('Share'),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.buttonGrey,
                            foregroundColor: AppColors.textDark,
                            elevation: 0,
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  SizedBox(
                    width: double.infinity,
                    height: 50,
                    child: ElevatedButton.icon(
                      onPressed: () => _launchYouTubeVideo(context),
                      icon: const Icon(Icons.open_in_new, size: 18),
                      label: const Text('Watch Original', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primaryRed,
                        foregroundColor: Colors.white,
                        elevation: 0,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}