import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:youtube_summary_app/features/youtube_summary/presentation/state/summary_provider.dart';
import '../../../../core/constants/app_colors.dart';

class FullSummaryScreen extends StatelessWidget {
  final String title;
  final String channelName;
  final String thumbnailUrl;
  final String content;
  final String videoUrl;
  final bool isTranscript;
  final String? channelProfileSummary;
  final List<String> previousSummaries;
  final RelevanceReport? relevanceReport;

  const FullSummaryScreen({
    super.key,
    required this.title,
    required this.channelName,
    required this.thumbnailUrl,
    required this.content,
    required this.videoUrl,
    required this.isTranscript,
    this.channelProfileSummary,
    this.previousSummaries = const [],
    this.relevanceReport,
  });

  Future<void> _launchYouTubeVideo(BuildContext context) async {
    final Uri url = Uri.parse(videoUrl);
    if (!await launchUrl(url, mode: LaunchMode.externalApplication)) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Could not open YouTube link: $videoUrl')),
        );
      }
    }
  }

  void _copyText(BuildContext context) {
    Clipboard.setData(ClipboardData(text: content));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Copied to clipboard!')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.background,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close, color: AppColors.textDark),
          onPressed: () => Navigator.pop(context),
        ),
        centerTitle: true,
        title: Text(
          isTranscript ? 'Full Transcript' : 'Full Summary',
          style: const TextStyle(color: AppColors.textDark, fontWeight: FontWeight.bold, fontSize: 18),
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  CachedNetworkImage(
                    imageUrl: thumbnailUrl,
                    width: double.infinity,
                    height: 220,
                    fit: BoxFit.cover,
                    placeholder: (context, url) => Container(color: Colors.grey[200]),
                  ),
                  
                  Padding(
                    padding: const EdgeInsets.all(24.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          title,
                          style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: AppColors.textDark, height: 1.3),
                        ),
                        const SizedBox(height: 12),
                        Text(
                          channelName.toUpperCase(),
                          style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.textGrey, letterSpacing: 1.0),
                        ),
                        
                        const SizedBox(height: 32),
                        
                        if (!isTranscript)
                          Container(
                            padding: const EdgeInsets.only(left: 16),
                            decoration: const BoxDecoration(
                              border: Border(left: BorderSide(color: AppColors.primaryRed, width: 3)),
                            ),
                            child: const Text(
                              'Insights generated by TubeSum AI.',
                              style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: AppColors.textDark),
                            ),
                          ),
                        
                        const SizedBox(height: 24),
                        Text(
                          content,
                          style: const TextStyle(
                            fontSize: 16,
                            color: Color(0xFF333333),
                            height: 1.6,
                          ),
                        ),

                        if (!isTranscript && channelProfileSummary != null && channelProfileSummary!.isNotEmpty) ...[
                          const SizedBox(height: 40),
                          const Text(
                            'ABOUT THE CREATOR',
                            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w800, color: AppColors.textGrey, letterSpacing: 1.2),
                          ),
                          const SizedBox(height: 12),
                          Text(
                            channelProfileSummary!,
                            style: TextStyle(fontSize: 14, color: AppColors.textDark.withOpacity(0.8), height: 1.5),
                          ),
                        ],

                        if (!isTranscript && previousSummaries.isNotEmpty) ...[
                          const SizedBox(height: 40),
                          const Text(
                            'PREVIOUS CONTEXT',
                            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w800, color: AppColors.textGrey, letterSpacing: 1.2),
                          ),
                          const SizedBox(height: 12),
                          ...previousSummaries.map((summary) => Padding(
                            padding: const EdgeInsets.only(bottom: 12.0),
                            child: Container(
                              padding: const EdgeInsets.all(12),
                              decoration: BoxDecoration(
                                color: AppColors.buttonGrey.withOpacity(0.5),
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Text(
                                "• $summary",
                                style: const TextStyle(fontSize: 13, color: AppColors.textDark, fontStyle: FontStyle.italic),
                              ),
                            ),
                          )).toList(),
                        ],

                        if (!isTranscript) ...[
                          const SizedBox(height: 40),
                          const Text(
                            'RELATED INTELLIGENCE',
                            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w800, color: AppColors.textGrey, letterSpacing: 1.2),
                          ),
                          const SizedBox(height: 12),
                          if (relevanceReport != null && relevanceReport!.isRelated)
                            ...relevanceReport!.similarSummaries.map((similar) => Padding(
                              padding: const EdgeInsets.only(bottom: 16.0),
                              child: InkWell(
                                onTap: () => launchUrl(Uri.parse('https://www.youtube.com/watch?v=${similar.videoId}'), mode: LaunchMode.externalApplication),
                                child: Container(
                                  padding: const EdgeInsets.all(16),
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                    borderRadius: BorderRadius.circular(12),
                                    border: Border.all(color: AppColors.buttonGrey),
                                    boxShadow: [
                                      BoxShadow(color: Colors.black.withOpacity(0.02), blurRadius: 5, offset: const Offset(0, 2))
                                    ],
                                  ),
                                  child: Row(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      ClipRRect(
                                        borderRadius: BorderRadius.circular(8),
                                        child: CachedNetworkImage(
                                          imageUrl: 'https://img.youtube.com/vi/${similar.videoId}/0.jpg',
                                          width: 100,
                                          height: 66,
                                          fit: BoxFit.cover,
                                          errorWidget: (context, url, error) => Container(
                                            width: 100,
                                            height: 66,
                                            color: Colors.grey[200],
                                            child: const Icon(Icons.error),
                                          ),
                                        ),
                                      ),
                                      const SizedBox(width: 16),
                                      Expanded(
                                        child: Column(
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Row(
                                              children: [
                                                const Icon(Icons.auto_awesome, color: Colors.amber, size: 14),
                                                const SizedBox(width: 6),
                                                Text(
                                                  '${(similar.similarity * 100).toStringAsFixed(0)}% Match',
                                                  style: const TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.amber),
                                                ),
                                              ],
                                            ),
                                            const SizedBox(height: 8),
                                            Text(
                                              similar.title,
                                              style: const TextStyle(fontSize: 15, fontWeight: FontWeight.bold, color: AppColors.textDark),
                                              maxLines: 2,
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                            const SizedBox(height: 4),
                                            Text(
                                              similar.channelName.toUpperCase(),
                                              style: const TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: AppColors.textGrey),
                                            ),
                                            const SizedBox(height: 8),
                                            Text(
                                              similar.summary,
                                              style: TextStyle(fontSize: 13, color: AppColors.textDark.withOpacity(0.7), height: 1.4),
                                              maxLines: 2,
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                            const SizedBox(height: 8),
                                            const Text(
                                              'Tap to watch on YouTube',
                                              style: TextStyle(fontSize: 11, color: AppColors.primaryRed, fontWeight: FontWeight.w600),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            )).toList()
                          else
                            Container(
                              padding: const EdgeInsets.all(20),
                              width: double.infinity,
                              decoration: BoxDecoration(
                                color: AppColors.buttonGrey.withOpacity(0.3),
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: AppColors.buttonGrey),
                              ),
                              child: Column(
                                children: const [
                                  Icon(Icons.hub_outlined, color: AppColors.textGrey, size: 32),
                                  SizedBox(height: 12),
                                  Text(
                                    'No related content discovered yet.',
                                    style: TextStyle(color: AppColors.textGrey, fontSize: 14, fontWeight: FontWeight.w500),
                                  ),
                                  SizedBox(height: 4),
                                  Text(
                                    'Try summarizing more videos to build your knowledge map.',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(color: AppColors.textGrey, fontSize: 12),
                                  ),
                                ],
                              ),
                            ),
                        ],
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, -5))
              ],
            ),
            child: SafeArea(
              child: Column(
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: ElevatedButton.icon(
                          onPressed: () => _copyText(context),
                          icon: const Icon(Icons.copy, size: 18),
                          label: const Text('Copy Text'),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.buttonGrey,
                            foregroundColor: AppColors.textDark,
                            elevation: 0,
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: ElevatedButton.icon(
                          onPressed: () {}, 
                          icon: const Icon(Icons.share, size: 18),
                          label: const Text('Share'),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.buttonGrey,
                            foregroundColor: AppColors.textDark,
                            elevation: 0,
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  SizedBox(
                    width: double.infinity,
                    height: 50,
                    child: ElevatedButton.icon(
                      onPressed: () => _launchYouTubeVideo(context),
                      icon: const Icon(Icons.open_in_new, size: 18),
                      label: const Text('Watch Original', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primaryRed,
                        foregroundColor: Colors.white,
                        elevation: 0,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}