// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQE4Xk8WtiBloQ0yVEENDK_QeA2OAx2jk',
    appId: '1:723380008177:ios:a70e6fcca6c369da5c6550',
    messagingSenderId: '723380008177',
    projectId: 'summary-6ffef',
    storageBucket: 'summary-6ffef.firebasestorage.app',
    iosBundleId: 'com.example.youtubeSummaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzsrIQ_8mNVONnU2fePTQpVuyRBaIDUQg',
    appId: '1:723380008177:web:e395724531c3a8895c6550',
    messagingSenderId: '723380008177',
    projectId: 'summary-6ffef',
    authDomain: 'summary-6ffef.firebaseapp.com',
    storageBucket: 'summary-6ffef.firebasestorage.app',
    measurementId: 'G-9K41JMV26D',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzsrIQ_8mNVONnU2fePTQpVuyRBaIDUQg',
    appId: '1:723380008177:web:e395724531c3a8895c6550',
    messagingSenderId: '723380008177',
    projectId: 'summary-6ffef',
    authDomain: 'summary-6ffef.firebaseapp.com',
    storageBucket: 'summary-6ffef.firebasestorage.app',
    measurementId: 'G-9K41JMV26D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQE4Xk8WtiBloQ0yVEENDK_QeA2OAx2jk',
    appId: '1:723380008177:ios:a70e6fcca6c369da5c6550',
    messagingSenderId: '723380008177',
    projectId: 'summary-6ffef',
    storageBucket: 'summary-6ffef.firebasestorage.app',
    iosBundleId: 'com.example.youtubeSummaryApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Qjf3ZPqvBkNAZWYDNb__bauvXUsVU5Y',
    appId: '1:723380008177:android:5c9858b0acf586c55c6550',
    messagingSenderId: '723380008177',
    projectId: 'summary-6ffef',
    storageBucket: 'summary-6ffef.firebasestorage.app',
  );

}